--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.applications (
    id integer NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    team character varying(255),
    contest_article character varying(255) NOT NULL
);


ALTER TABLE public.applications OWNER TO postgres;

--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contest_files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contest_files (
    id integer NOT NULL,
    file character varying(255) NOT NULL,
    contest_article character varying(255) NOT NULL
);


ALTER TABLE public.contest_files OWNER TO postgres;

--
-- Name: contest_files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contest_files ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.contest_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contest_statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contest_statuses (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.contest_statuses OWNER TO postgres;

--
-- Name: contest_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contest_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contest_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contests (
    id integer NOT NULL,
    name character varying(255) DEFAULT ''::character varying NOT NULL,
    article character varying(50) NOT NULL,
    status_id integer DEFAULT 1 NOT NULL,
    info text DEFAULT ''::text NOT NULL,
    organizer text DEFAULT ''::text NOT NULL,
    sponsor text DEFAULT ''::text NOT NULL,
    rules text DEFAULT ''::text NOT NULL,
    timetable text DEFAULT ''::text NOT NULL,
    results text DEFAULT ''::text NOT NULL,
    materials text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.contests OWNER TO postgres;

--
-- Name: contests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contests ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.contests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.members (
    id integer NOT NULL,
    fio character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    organization character varying(255),
    application_id integer NOT NULL,
    is_trainer boolean DEFAULT false NOT NULL
);


ALTER TABLE public.members OWNER TO postgres;

--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" (id, login, password) FROM stdin;
1	admin	$2a$10$gwh1HHVqgN.tZI4XADod4.8sWpnS/k30wi.QzUvyjy0s8jhuXuZY6
\.


--
-- Data for Name: applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.applications (id, status, team, contest_article) FROM stdin;
\.


--
-- Data for Name: contest_files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contest_files (id, file, contest_article) FROM stdin;
\.


--
-- Data for Name: contest_statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contest_statuses (id, name) FROM stdin;
1	Скрыто
2	Объявление соревнования
3	Открытие регистрации
4	Завершение регистрации
5	Старт соревнования
6	Завершение соревнования
7	Публикация материалов
8	В архиве
\.


--
-- Data for Name: contests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contests (id, name, article, status_id, info, organizer, sponsor, rules, timetable, results, materials) FROM stdin;
\.


--
-- Data for Name: members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.members (id, fio, email, phone, organization, application_id, is_trainer) FROM stdin;
\.


--
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_id_seq"', 1, true);


--
-- Name: applications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.applications_id_seq', 12, true);


--
-- Name: contest_files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contest_files_id_seq', 12, true);


--
-- Name: contest_statuses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contest_statuses_id_seq', 8, true);


--
-- Name: contests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contests_id_seq', 66, true);


--
-- Name: members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.members_id_seq', 18, true);


--
-- Name: Users Users_login_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_login_key" UNIQUE (login);


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: contest_files contest_files_file_contest_article_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contest_files
    ADD CONSTRAINT contest_files_file_contest_article_key UNIQUE (file, contest_article);


--
-- Name: contest_files contest_files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contest_files
    ADD CONSTRAINT contest_files_pkey PRIMARY KEY (id);


--
-- Name: contest_statuses contest_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contest_statuses
    ADD CONSTRAINT contest_statuses_pkey PRIMARY KEY (id);


--
-- Name: contests contests_article_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_article_key UNIQUE (article);


--
-- Name: contests contests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: applications applications_contest_article_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_contest_article_fkey FOREIGN KEY (contest_article) REFERENCES public.contests(article) NOT VALID;


--
-- Name: contest_files contest_files_contest_article_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contest_files
    ADD CONSTRAINT contest_files_contest_article_fkey FOREIGN KEY (contest_article) REFERENCES public.contests(article) NOT VALID;


--
-- Name: contests contests_status_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contests
    ADD CONSTRAINT contests_status_fkey FOREIGN KEY (status_id) REFERENCES public.contest_statuses(id) NOT VALID;


--
-- Name: members members_application_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id) NOT VALID;


--
-- Name: TABLE "Users"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."Users" TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE "Users_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."Users_id_seq" TO sport WITH GRANT OPTION;


--
-- Name: TABLE applications; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.applications TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE applications_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.applications_id_seq TO sport WITH GRANT OPTION;


--
-- Name: TABLE contest_files; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.contest_files TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE contest_files_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.contest_files_id_seq TO sport WITH GRANT OPTION;


--
-- Name: TABLE contest_statuses; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.contest_statuses TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE contest_statuses_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.contest_statuses_id_seq TO sport WITH GRANT OPTION;


--
-- Name: TABLE contests; Type: ACL; Schema: public; Owner: postgres
--

REVOKE ALL ON TABLE public.contests FROM postgres;
GRANT ALL ON TABLE public.contests TO postgres WITH GRANT OPTION;
GRANT ALL ON TABLE public.contests TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE contests_id_seq; Type: ACL; Schema: public; Owner: postgres
--

REVOKE ALL ON SEQUENCE public.contests_id_seq FROM postgres;
GRANT ALL ON SEQUENCE public.contests_id_seq TO postgres WITH GRANT OPTION;
GRANT ALL ON SEQUENCE public.contests_id_seq TO sport WITH GRANT OPTION;


--
-- Name: TABLE members; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.members TO sport WITH GRANT OPTION;


--
-- Name: SEQUENCE members_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.members_id_seq TO sport WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

